### ISSUE TITLE
Remove all external dependencies and add them locally

### ISSUE THREAD

**Issue by singhabahu** [team-entropy/web-review#3]
As it's required to host this site in an intranet where it doesn't have internet connectivity it's a must to remove all the dependencies and have them locally.

- Refer to CDNs and get them locally available 
- Minify them as we are bound to 20MB hard limit
- Try to complete within a day

**Comment by GudarJs** [comment]
May I help you with this?

**Comment by saadsahibjan** [comment]
This has been fixed by #4 
@singhabahu hope we can resolve this issue

**Comment by singhabahu** [comment]
@saadsahibjan yes. Let's close this.
